### ISSUE TITLE
Not showing anything

### ISSUE THREAD

**Issue by TitouBilou** [mykle1/MMM-EveryNews#2]
Hi there,
I've installed the module, everything went smoothly, MM and modules are up to date but the only thing I see is "AnyNews Presents..." Never seems to get the RSS feed (I've tried different sources). Could it be because I have multiple pages on my MM (carousel) and the module is only shown on one of them?
Thanx,
Titou.

**Comment by mykle1** [comment]
It's possible, maybe even likely, but I don't know and I don't use carousel to test. I do know that the module works as expected. You could try to disable the carousel and see if the module loads then. DId you get an api key? That's required.
