### ISSUE TITLE
Conflict with MMM-GoogleMapsTraffic

### ISSUE THREAD

**Issue by Dimasua** [mykle1/MMM-EveryNews#3]
When I'm running [MMM-GoogleMapsTraffic](https://github.com/vicmora/MMM-GoogleMapsTraffic) Module the MMM-EveryNews stops working and displays only "AnyNews presents..." message. This dependency has been proven by making the  MMM-GoogleMapsTraffic module several times false and true, and MMM-EveryNews was back to normal every time MMM-GoogleMapsTraffic was off.
What can be conflicting and hindering here?

**Comment by mykle1** [comment]
I see on the forum that the issue was with GoogleMapsTraffic, not this module
