### ISSUE TITLE
Having issues calling module multiple times with different sources

### ISSUE THREAD

**Issue by juan9999** [mykle1/MMM-EveryNews#4]
I'm trying to create an apple news like feed by having multiple instances of MMM-EveryNews

1. I duplicated the module folder in the \module folder to create \MMM_EveryNews1, ...2 etc
2. I renamed the .js file in each directory 
3. I edited the .js file to register different module name

I tried to call the module three times at three different locations (bottom_left, bottom_right...) with different sources in each.

Unfortunately, all the center module (no matter what source I put in it) doesn't respect the width and the image preview overlaps with the bottom right

I didn't change or rename the .css

**Comment by mykle1** [comment]
The module was not designed to work that way. Some do, some don't. If it is going to work:
1. You would have to rename the corresponding css files to match each new copy of the module
2. Rename the classes inside the duplicate css files.
3. In each js file, rename the "get scripts" to reflect the corresponding css file names

Seeing as this is not really an issue, I am closing this
